### ISSUE TITLE
Set up integration test framework

### ISSUE THREAD

**Issue by ds300** [ds300/lazyrepo#11]
At a minimum we should have a way to create a temp dir on disk and populate it with a pnpm/yarn/npm workspaces setup matching some given config object, then returning a link to the dir to use in tests, along with setting up the workspace root and automating cleanup logic.

Maybe something like 

```
function runTestInProject(config, async (dir) => {
  // do the test logic
})
```

Look at [wireit](https://github.com/google/wireit) for possible prior art.

**Comment by mrkldshv** [comment]
I'm refactoring some parts of the CLI now, and integration tests of the commands would've been great to confirm I didn't break anything :) I think we should be able to use jest for this type of fs setup and cleanup, though I'm not sure how easy it would be to implement. Do you have any other ideas for the integration tests framework?

**Comment by mrkldshv** [comment]
Sure, no worries! Sorry for the poor phrasing. I didn't mean to point out the absence of some tests ❤️ 
It was more of a side note under this issue for us.
