### ISSUE TITLE
Include global inputs in manifests

### ISSUE THREAD

**Issue by ds300** [ds300/lazyrepo#12]
This involves:

- Implementing support for the `globalDependencies` (let's rename to `globalIncludes`) and `globalExcludes` options.
- Adding support for a global env vars option: `globalEnvInputs` (also rename `inputEnvVars` in task config to `envInputs`)
- Thinking about what the default values of `globalIncludes` and `globalExcludes` should be, if anything. Not important to get it right immediately, but take a look at what turbo and wireit do at least.

**Comment by ds300** [comment]
It refers to files and env vars that should be included in every task's input manifest. I'm working on this right now since we need it at tldraw and am currently thinking it should be called `commonCacheConfig` or something.

**Comment by judicaelandria** [comment]
drop the `common` (😄)  just `cacheConfigs`

**Comment by ds300** [comment]
haha merged already sorry. but yeah now that I think about it `common` is a slightly awkward word. i might change it to `shared`

**Comment by ds300** [comment]
Actually 'baseCacheConfig' might be even better?
