### ISSUE TITLE
Add validation for config file

### ISSUE THREAD

**Issue by mrkldshv** [ds300/lazyrepo#13]
We should validate configuration file and provide helpful error message if the config doesn't match provided schema.

**Comment by ds300** [comment]
Absolutely! I'm interested in maybe trying https://github.com/Effect-TS/schema instead of zod, since it seems light weight and flexible, if a little abstract. And we can also use it to generate a json schema file for folks who are particularly into json config files.

**Comment by ds300** [comment]
see also #16

**Comment by mrkldshv** [comment]
I'm looking into this one, and from the quick test it seems that Effect-TS schema is heavier than zod. I checked a few code snippets from the docs on bundle.js and packagephobia. I might be looking at the wrong thing though so I'll test it locally as well.
