### ISSUE TITLE
Add support for TypeScript config file

### ISSUE THREAD

**Issue by mrkldshv** [ds300/lazyrepo#3]
We should add support for configuration files with `ts` and `mts` file extensions. We can use TypeScript API or esbuild to transpile code to JavaScript.

**Comment by ds300** [comment]
Yeah I'd love this as long as it doesn't add any noticeable startup slowdown.

**Comment by mrkldshv** [comment]
Right, I'm going to check the impact on the startup time. Will submit PR soon :)
