### ISSUE TITLE
Make stack traces in TS config files clickable

### ISSUE THREAD

**Issue by ds300** [ds300/lazyrepo#30]
Followup to #4

When lazyrepo loads a .ts config file via esbuild, the filenames in the stacktrackes of any errors thrown are prefixed by `file:///private/` for some reason. This makes them unclickable in terminal output.

![Image](https://user-images.githubusercontent.com/1242537/231740938-49bcc645-d115-413c-98d7-4c45498de0bc.png)

This task is to find a way to strip those prefixes out. I assume there's a way we can configure esbuild to not do that. If not, it's no big deal.

**Comment by ds300** [comment]
Hmm maybe we can save it in the .lazy folder in that case?

**Comment by mrkldshv** [comment]
Yeah, we can do that. Will submit the fix now!
