### ISSUE TITLE
Change throwOnError to expectError

### ISSUE THREAD

**Issue by ds300** [ds300/lazyrepo#63]
The `TestHarness.exec` method takes a `throwOnError` with a default value of `true`. Let's replace it with an `expectError` flag with a default value of `false`, to clarify the intent of the flag.

**Comment by ds300** [comment]
- if `expectError` is `true` and the process returns with exit code 0, it should throw an error and fail the test
- if `expectError` is `true` and the process returns with exit code 1, it should return the output and status code
- if `expectError` is `false` and the process returns with exit code 0, it should return the output and status code
- if `expectError` is `false` and the process returns with exit code 1, it should throw an error and fail the test
- the default value of `expectError` should be `false`

**Comment by mrkldshv** [comment]
Thanks, sounds good! It's clear now.
